server:
  port: ${HTTPS_PORT:8080}
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEY_STORE:}
    key-store-password: ${SSL_KEY_STORE_PASSWORD:}
    key-store-type: PKCS12
    key-alias: ${SSL_KEY_ALIAS:}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: techcup-futbol
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME}
      password: ${SPRING_SECURITY_USER_PASSWORD}
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/techcup?stringtype=unspecified}
    username: ${DB_USER:techcup_owner}
    password: ${DB_PASSWORD:techcup123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    "com.escuela.techcup": DEBUG
  file:
    name: logs/api.log

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}