spring.application.name=techcup-futbol
spring.security.user.name=admin
spring.security.user.password=1234

# application.properties
logging.level.root=INFO
logging.level.com.escuela.techcup=DEBUG
logging.file.name=logs/api.log

# JWT Configuration
jwt.secret=test-secret-key-for-jwt-signing-must-be-long-enough-for-security-purposes-change-this-in-production-xd
jwt.expiration=86400000