server:
  port: ${HTTPS_PORT}
  ssl:
    enabled: ${SSL_ENABLED:true}
    key-store: ${SSL_KEY_STORE:classpath:certs/techup-local.p12}
    key-store-password: ${SSL_KEY_STORE_PASSWORD:changeit}
    key-store-type: PKCS12
    key-alias: ${SSL_KEY_ALIAS:techup-local}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: techcup-futbol
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME}
      password: ${SPRING_SECURITY_USER_PASSWORD}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/techcup}
    username: techcup_owner
    password: techcup123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    "com.escuela.techcup": DEBUG
  file:
    name: logs/api.log

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}