spring.application.name=techcup-futbol
spring.security.user.name=admin
spring.security.user.password=1234

# application.properties
logging.level.root=INFO
logging.level.com.escuela.techcup=DEBUG
logging.file.name=logs/api.log